[context.production.environment]
  HUGO_VERSION = "v0.83.1"
[build]
publish = "public"
command = "hugo --gc --minify" 
#[build.processing]
#    skip_processing = true
[[redirects]]
  from = "/proposta/*"
  status = 200
  force = true
  conditions = {Role = ["pro"]}

[[redirects]]
  from = "/proposta/*"
  to = "/.netlify/functions/redirect"
  status = 200
  force = true
[functions]
  directory = "functions"
