[context.production.environment]
#  HUGO_VERSION = "v0.83.1"
  HUGO_VERSION = "v0.112.3"
  HUGO_ENV = "production"

[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
    cloudName = "gawzkqk2d35eo9"
    loadingStrategy = "eager"

[build]
publish = "public"
command = "hugo --gc --minify && cp _headers public/"
#command = "hugo --minify && brotli public/**/*.{css,js}"
#[build.processing]
#    skip_processing = true
[[redirects]]
  from = "/proposta/*"
  status = 200
  force = true
  conditions = {Role = ["pro"]}

[[redirects]]
  from = "/proposta/*"
  to = "/.netlify/functions/redirect"
  status = 200
  force = true
[functions]
  directory = "functions"

[[redirects]]
from = "/*"
to = "/404.html"
status = 404

[[redirects]]
from = "/en/*"
to = "/en/404.html"
status = 404

[[redirects]]
from = "/de/*"
to = "/de/404.html"
status = 404

[[redirects]]
from = "/fr/*"
to = "/de/404.html"
status = 404

[[redirects]]
from = "/es/*"
to = "/de/404.html"
status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
