[context.production.environment]
#  HUGO_VERSION = "v0.83.1"
  HUGO_VERSION = "v0.126.1"
  HUGO_ENV = "production"

[[plugins]]
   package = "netlify-plugin-cloudinary"

   [plugins.inputs]
     cloudName = "gawzkqk2d35eo9"
     loadingStrategy = "eager"

[build]
publish = "public"
#command = "hugo --gc --minify && cp _headers public/ && cp _redirects public/"
command = "hugo --gc --minify"
#command = "hugo --minify && brotli public/**/*.{css,js}"
#[build.processing]
#    skip_processing = true
#environment = { BROTLI_COMPRESSION = "9" }

[[redirects]]
  from = "/proposta/*"
  status = 200
  force = true
  conditions = {Role = ["pro"]}

[[redirects]]
  from = "/proposta/*"
  to = "/.netlify/functions/redirect"
  status = 200
  force = true
[functions]
  directory = "functions"

[[redirects]]
from = "/*"
to = "/404.html"
status = 404

[[redirects]]
from = "/en/*"
to = "/en/404.html"
status = 404

[[redirects]]
from = "/de/*"
to = "/de/404.html"
status = 404

[[redirects]]
from = "/fr/*"
to = "/de/404.html"
status = 404

[[redirects]]
from = "/es/*"
to = "/de/404.html"
status = 404

[[redirects]]
from = "/old/*"
to = "/new/"
status = 200

[[redirects]]
  from = "/.well-known/*"
  to = "/well-known/"
  status = 200
