[context.production.environment]
#  HUGO_VERSION = "v0.83.1"
  HUGO_VERSION = "v0.112.3"
  HUGO_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/{path}.html"
  status = 200
  force = true
  headers = {Content-Type = "text/html; charset=utf-8", "Cache-Control" = "public, max-age=0, must-revalidate"}

[[redirects]]
  from = "/*.css"
  to = "/{path}.css"
  status = 200
  force = true
  headers = {"Content-Type"="text/css", "Cache-Control"="public, max-age=31536000, immutable"}

[[redirects]]
  from = "/*.js"
  to = "/{path}.js"
  status = 200
  force = true
  headers = {"Content-Type"="application/javascript", "Cache-Control"="public, max-age=31536000, immutable"}

[[redirects]]
  from = "/*.svg"
  to = "/{path}.svg"
  status = 200
  force = true
  headers = {"Content-Type"="image/svg+xml", "Cache-Control"="public, max-age=31536000, immutable"}

[[headers]]
  for = "/**/*.@(html|css|js|svg)"
  [headers.values]
    Content-Encoding = "gzip"
    Cache-Control = "public, max-age=31536000, immutable"

[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
    cloudName = "gawzkqk2d35eo9"
    loadingStrategy = "eager"

[build]
publish = "public"
command = "hugo --gc --minify" 
#[build.processing]
#    skip_processing = true
[[redirects]]
  from = "/proposta/*"
  status = 200
  force = true
  conditions = {Role = ["pro"]}

[[redirects]]
  from = "/proposta/*"
  to = "/.netlify/functions/redirect"
  status = 200
  force = true
[functions]
  directory = "functions"

[[redirects]]
from = "/*"
to = "/404.html"
status = 404

[[redirects]]
from = "/en/*"
to = "/en/404.html"
status = 404

[[redirects]]
from = "/de/*"
to = "/de/404.html"
status = 404

[[redirects]]
from = "/fr/*"
to = "/de/404.html"
status = 404

[[redirects]]
from = "/es/*"
to = "/de/404.html"
status = 404
