[build]
publish = "public"
command = "hugo  --baseURL=https://www.gasparsantos.eu"

[build.environment]
HUGO_VERSION = "0.34"

[context.dev]
command = "hugo  --baseURL=https://dev--www.gasparsantos.eu"
