backend:
  name: git-gateway
#  branch: main # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
publish_mode: editorial_workflow
site_url: https://www.gasparsantos.eu
logo_url: https://your-site.com/images/favicon.png
collections:
  - name: 'page'
    label: 'Page'
    folder: 'content/page'
    create: true
    slug: '{{title}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'concertos'
    label: 'Concertos'
    folder: 'content/concertos'
    create: true
    slug: '{{title}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
