backend:
  name: git-gateway
#  branch: main # Branch to update (optional; defaults to master)
local_backend: true
media_folder: static/images
public_folder: /images
publish_mode: editorial_workflow
site_url: https://www.gasparsantos.eu
logo_url: https://www.gasparsantos.eu/images/favicon.png
i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [pt, en, de, fr, es]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: pt
collections:
  - name: 'page'
    label: 'Page'
    folder: 'content/page'
    create: true
    i18n: true
    slug: '{{title}}'
    editor:
      preview: true
    fields:
      - { label: "Draft", name: "draft", widget: "boolean", default: "true", i18n: duplicate }
      - { label: "Slug", name: "slug", widget: "string", default: "{{slug}}", i18n: true }
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', i18n: duplicate }
      - { label: 'Description', name: 'description', widget: 'string', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
  - name: 'concertos'
    label: 'Concertos'
    folder: 'content/concertos'
    create: true
    i18n: true
    slug: '{{title}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', i18n: duplicate }
      - { label: 'Description', name: 'description', widget: 'string', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
